
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xxxvethernet.h"

/*
* The configuration table for devices
*/

XXxvEthernet_Config XXxvEthernet_ConfigTable[] =
{
	{
		XPAR_XXVETHERNET_0_DEVICE_ID,
		XPAR_XXVETHERNET_0_BASEADDR,
		XPAR_XXVETHERNET_0_STATS
	}
};

